// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from {{data.Filename}} - do not modify

#include "Actions/ROS2{{data.UEName}}.h"

{{data.GoalConstantsDef}}
{{data.ResultConstantsDef}}
{{data.FeedbackConstantsDef}}

const rosidl_action_type_support_t* UROS2{{data.UEName}}Action::GetTypeSupport() const
{
    return ROSIDL_GET_ACTION_TYPE_SUPPORT({{data.Group}}, {{data.NameCap}});
}

void UROS2{{data.UEName}}Action::Init()
{
    Super::Init();
    {{data.Group}}__action__{{data.NameCap}}_SendGoal_Request__init(&{{data.NameCap}}_goal_request);
    {{data.Group}}__action__{{data.NameCap}}_SendGoal_Response__init(&{{data.NameCap}}_goal_response);
    {{data.Group}}__action__{{data.NameCap}}_GetResult_Request__init(&{{data.NameCap}}_result_request);
    {{data.Group}}__action__{{data.NameCap}}_GetResult_Response__init(&{{data.NameCap}}_result_response);
    {{data.Group}}__action__{{data.NameCap}}_FeedbackMessage__init(&{{data.NameCap}}_feedback_message);
}

void UROS2{{data.UEName}}Action::Fini()
{
    {{data.Group}}__action__{{data.NameCap}}_SendGoal_Request__fini(&{{data.NameCap}}_goal_request);
    {{data.Group}}__action__{{data.NameCap}}_SendGoal_Response__fini(&{{data.NameCap}}_goal_response);
    {{data.Group}}__action__{{data.NameCap}}_GetResult_Request__fini(&{{data.NameCap}}_result_request);
    {{data.Group}}__action__{{data.NameCap}}_GetResult_Response__fini(&{{data.NameCap}}_result_response);
    {{data.Group}}__action__{{data.NameCap}}_FeedbackMessage__fini(&{{data.NameCap}}_feedback_message);
    Super::Fini();
}

void UROS2{{data.UEName}}Action::SetGoalRequest(const FROS{{data.UEName}}SGReq& Goal)
{
    Goal.SetROS2({{data.NameCap}}_goal_request);
}

void UROS2{{data.UEName}}Action::GetGoalRequest(FROS{{data.UEName}}SGReq& Goal) const
{
    Goal.SetFromROS2({{data.NameCap}}_goal_request);
}

void UROS2{{data.UEName}}Action::SetGoalResponse(const FROS{{data.UEName}}SGRes& Goal)
{
    Goal.SetROS2({{data.NameCap}}_goal_response);
}

void UROS2{{data.UEName}}Action::GetGoalResponse(FROS{{data.UEName}}SGRes& Goal) const
{
    Goal.SetFromROS2({{data.NameCap}}_goal_response);
}

void UROS2{{data.UEName}}Action::SetResultRequest(const FROS{{data.UEName}}GRReq& Result)
{
    Result.SetROS2({{data.NameCap}}_result_request);
}

void UROS2{{data.UEName}}Action::GetResultRequest(FROS{{data.UEName}}GRReq& Result) const
{
    Result.SetFromROS2({{data.NameCap}}_result_request);
}

void UROS2{{data.UEName}}Action::SetResultResponse(const FROS{{data.UEName}}GRRes& Result)
{
    Result.SetROS2({{data.NameCap}}_result_response);
}

void UROS2{{data.UEName}}Action::GetResultResponse(FROS{{data.UEName}}GRRes& Result) const
{
    Result.SetFromROS2({{data.NameCap}}_result_response);
}


void UROS2{{data.UEName}}Action::SetFeedback(const FROS{{data.UEName}}FB& Feedback)
{
    Feedback.SetROS2({{data.NameCap}}_feedback_message);
}

void UROS2{{data.UEName}}Action::GetFeedback(FROS{{data.UEName}}FB& Feedback) const
{
    Feedback.SetFromROS2({{data.NameCap}}_feedback_message);
}

void UROS2{{data.UEName}}Action::SetGoalIdToFeedback(FROS{{data.UEName}}FB& Feedback)
{
    for (int i = 0; i < 16; i++)
    {
        Feedback.GoalId[i] = {{data.NameCap}}_goal_request.goal_id.uuid[i];
    }
}

void* UROS2{{data.UEName}}Action::GetGoalRequest()
{
    return &{{data.NameCap}}_goal_request;
}

void* UROS2{{data.UEName}}Action::GetGoalResponse()
{
    return &{{data.NameCap}}_goal_response;
}

void* UROS2{{data.UEName}}Action::GetResultRequest()
{
    return &{{data.NameCap}}_result_request;
}

void* UROS2{{data.UEName}}Action::GetResultResponse()
{
    return &{{data.NameCap}}_result_response;
}

void* UROS2{{data.UEName}}Action::GetFeedbackMessage()
{
    return &{{data.NameCap}}_feedback_message;
}
