// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from {{data.Filename}} - do not modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "unique_identifier_msgs/msg/uuid.h"
#include "{{data.Group}}/action/{{data.Name}}.h"
#include "action_msgs/srv/cancel_goal.h"

// rclUE
#include "Actions/ROS2GenericAction.h"
#include "rclcUtilities.h"


// Generated Msg/Srv/Action(can be empty)
{{data.GoalHeaders}}
{{data.ResultHeaders}}
{{data.FeedbackHeaders}}

// Generated
#include "ROS2{{data.UEName}}.generated.h"

USTRUCT(Blueprintable)
struct {{data.ModuleAPI}} FROS{{data.UEName}}SGReq
{
	GENERATED_BODY()

public:
	{{data.GoalConstantsDec}}
  	
	TArray<uint8, TFixedAllocator<16>> GoalId;

	{{data.GoalTypes}}

	FROS{{data.UEName}}SGReq()
    {
        UROS2Utils::GenerateRandomUUID16(GoalId);
		{{data.GoalConstructor}}
    }

	void SetFromROS2(const {{data.Group}}__action__{{data.NameCap}}_SendGoal_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	{{data.GoalSetFromROS2}}
	}

	void SetROS2({{data.Group}}__action__{{data.NameCap}}_SendGoal_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	{{data.GoalSetROS2}}
	}
};

USTRUCT(Blueprintable)
struct {{data.ModuleAPI}} FROS{{data.UEName}}SGRes
{
	GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bAccepted = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Stamp = 0.f;

    void SetFromROS2(const {{data.Group}}__action__{{data.NameCap}}_SendGoal_Response& in_ros_data)
    {
        bAccepted = in_ros_data.accepted;
        Stamp = UROS2Utils::ROSStampToFloat(in_ros_data.stamp);
    }

    void SetROS2({{data.Group}}__action__{{data.NameCap}}_SendGoal_Response& out_ros_data) const
    {
        out_ros_data.accepted = bAccepted;
        out_ros_data.stamp = UROS2Utils::FloatToROSStamp(Stamp);
    }
};

USTRUCT(Blueprintable)
struct {{data.ModuleAPI}} FROS{{data.UEName}}GRReq
{
	GENERATED_BODY()

public:
  	TArray<uint8, TFixedAllocator<16>> GoalId;

    FROS{{data.UEName}}GRReq()
    {
        GoalId.Init(0, 16);
    }

	void SetFromROS2(const {{data.Group}}__action__{{data.NameCap}}_GetResult_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

	}

	void SetROS2({{data.Group}}__action__{{data.NameCap}}_GetResult_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}
	}
};

USTRUCT(Blueprintable)
struct {{data.ModuleAPI}} FROS{{data.UEName}}GRRes
{
	GENERATED_BODY()

public:
	{{data.ResultConstantsDec}}

	UPROPERTY()
	int8 GRResStatus = 0;

	{{data.ResultTypes}}

	FROS{{data.UEName}}GRRes()
    {
		{{data.ResultConstructor}}
    }

	void SetFromROS2(const {{data.Group}}__action__{{data.NameCap}}_GetResult_Response& in_ros_data)
	{
		GRResStatus = in_ros_data.status;
    	{{data.ResultSetFromROS2}}
	}

	void SetROS2({{data.Group}}__action__{{data.NameCap}}_GetResult_Response& out_ros_data) const
	{
		out_ros_data.status = GRResStatus;
    	{{data.ResultSetROS2}}
	}
};

USTRUCT(Blueprintable)
struct {{data.ModuleAPI}} FROS{{data.UEName}}FB
{
	GENERATED_BODY()

public:
	{{data.FeedbackConstantsDec}}

  	TArray<uint8, TFixedAllocator<16>> GoalId;

	{{data.FeedbackTypes}}


    FROS{{data.UEName}}FB()
    {
        GoalId.Init(0, 16);
		{{data.FeedbackConstructor}}
    }

	void SetFromROS2(const {{data.Group}}__action__{{data.NameCap}}_FeedbackMessage& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	{{data.FeedbackSetFromROS2}}
	}

	void SetROS2({{data.Group}}__action__{{data.NameCap}}_FeedbackMessage& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}
		
    	{{data.FeedbackSetROS2}}
	}
};

UCLASS()
class {{data.ModuleAPI}} UROS2{{data.UEName}}Action : public UROS2GenericAction
{
	GENERATED_BODY()
	
public:
	virtual void Init() override;

	virtual void Fini() override;

	virtual const rosidl_action_type_support_t* GetTypeSupport() const override;

  	UFUNCTION(BlueprintCallable)
	void SetGoalRequest(const FROS{{data.UEName}}SGReq& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalRequest(FROS{{data.UEName}}SGReq& Goal) const;
	
  	UFUNCTION(BlueprintCallable)
	void SetGoalResponse(const FROS{{data.UEName}}SGRes& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalResponse(FROS{{data.UEName}}SGRes& Goal) const;
	
  	UFUNCTION(BlueprintCallable)
	void SetResultRequest(const FROS{{data.UEName}}GRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultRequest(FROS{{data.UEName}}GRReq& Result) const;
	
  	UFUNCTION(BlueprintCallable)
	void SetResultResponse(const FROS{{data.UEName}}GRRes& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultResponse(FROS{{data.UEName}}GRRes& Result) const;

  	UFUNCTION(BlueprintCallable)
	void SetFeedback(const FROS{{data.UEName}}FB& Feedback);

  	UFUNCTION(BlueprintCallable)
	void GetFeedback(FROS{{data.UEName}}FB& Feedback) const;
	
  	UFUNCTION(BlueprintCallable)
	void SetGoalIdToFeedback(FROS{{data.UEName}}FB& Feedback);

	virtual void* GetGoalRequest() override;
	virtual void* GetGoalResponse() override;
	virtual void* GetResultRequest() override;
	virtual void* GetResultResponse() override;
	virtual void* GetFeedbackMessage() override;

	{{data.GoalConstantsGetter}}
	{{data.ResultConstantsGetter}}
	{{data.FeedbackConstantsGetter}}

private:
	{{data.Group}}__action__{{data.NameCap}}_SendGoal_Request {{data.NameCap}}_goal_request;
	{{data.Group}}__action__{{data.NameCap}}_SendGoal_Response {{data.NameCap}}_goal_response;
	{{data.Group}}__action__{{data.NameCap}}_GetResult_Request {{data.NameCap}}_result_request;
	{{data.Group}}__action__{{data.NameCap}}_GetResult_Response {{data.NameCap}}_result_response;
	{{data.Group}}__action__{{data.NameCap}}_FeedbackMessage {{data.NameCap}}_feedback_message;
};
