// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from {{data.Filename}} - do not modify

#pragma once

#include "CoreMinimal.h"

#include "{{data.Group}}/msg/{{data.Name}}.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2{{data.NameCap}}Msg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API F{{data.StructName}}
{
	GENERATED_BODY()

public:
	{{data.Types}}

	void SetFromROS2({{data.Group}}__msg__{{data.NameCap}} rosdata)
	{
    	{{data.SetFromROS2}}
	}

	void SetROS2({{data.Group}}__msg__{{data.NameCap}}& rosdata) const
	{
    	{{data.SetROS2}}
	}
};

UCLASS()
class RCLUE_API UROS2{{data.NameCap}}Msg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const F{{data.StructName}} Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(F{{data.StructName}}& Output) const;
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	{{data.Group}}__msg__{{data.NameCap}} {{data.Name}}_msg;
};
