// Copyright 2023 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from {{data.Filename}} - do not modify

#include "Msgs/ROS2{{data.UEName}}.h"

#include "Kismet/GameplayStatics.h"

{{data.ConstantsDef}}

void UROS2{{data.UEName}}Msg::Init()
{
	{{data.Group}}__msg__{{data.NameCap}}__init(&{{data.Name}}_msg);
}

void UROS2{{data.UEName}}Msg::Fini()
{
	{{data.Group}}__msg__{{data.NameCap}}__fini(&{{data.Name}}_msg);
}

const rosidl_message_type_support_t* UROS2{{data.UEName}}Msg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT({{data.Group}}, msg, {{data.NameCap}});
}

void UROS2{{data.UEName}}Msg::SetMsg(const FROS{{data.UEName}}& Inputs)
{
    Inputs.SetROS2({{data.Name}}_msg);
}

void UROS2{{data.UEName}}Msg::GetMsg(FROS{{data.UEName}}& Outputs) const
{
    Outputs.SetFromROS2({{data.Name}}_msg);
}

void* UROS2{{data.UEName}}Msg::Get()
{
	return &{{data.Name}}_msg;
}

FString UROS2{{data.UEName}}Msg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}