// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from {{data.Filename}} - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "{{data.Group}}/msg/{{data.Name}}.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
{{data.Headers}}

// Generated
#include "ROS2{{data.UEName}}.generated.h"

USTRUCT(Blueprintable)
struct {{data.ModuleAPI}} FROS{{data.UEName}}
{
	GENERATED_BODY()

public:
	{{data.ConstantsDef}}

	{{data.Types}}

	FROS{{data.UEName}}()
	{
		{{data.Constructor}}
	}

	void SetFromROS2(const {{data.Group}}__msg__{{data.NameCap}}& in_ros_data)
	{
    	{{data.SetFromROS2}}
	}

	void SetROS2({{data.Group}}__msg__{{data.NameCap}}& out_ros_data) const
	{
    	{{data.SetROS2}}
	}
};

UCLASS()
class {{data.ModuleAPI}} UROS2{{data.UEName}}Msg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROS{{data.UEName}}& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROS{{data.UEName}}& Output) const;
	
	virtual void* Get() override;

	{{data.ConstantsGetter}}


private:
	virtual FString MsgToString() const override;

	{{data.Group}}__msg__{{data.NameCap}} {{data.Name}}_msg;
};
