// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from {{data.Filename}} - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "{{data.Group}}/srv/{{data.Name}}.h"

// rclUE
#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
{{data.ReqHeaders}}
{{data.ResHeaders}}

// Generated
#include "ROS2{{data.UEName}}.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct {{data.ModuleAPI}} FROS{{data.UEName}}Req
{
	GENERATED_BODY()

public:
	{{data.ReqConstantsDec}}

	{{data.ReqTypes}}

	FROS{{data.UEName}}Req()
	{
		{{data.ReqConstructor}}
	}

	void SetFromROS2(const {{data.Group}}__srv__{{data.NameCap}}_Request& in_ros_data)
	{
    	{{data.ReqSetFromROS2}}
	}

	void SetROS2({{data.Group}}__srv__{{data.NameCap}}_Request& out_ros_data) const
	{
    	{{data.ReqSetROS2}}
	}
};

USTRUCT(Blueprintable)
struct {{data.ModuleAPI}} FROS{{data.UEName}}Res
{
	GENERATED_BODY()

public:
	{{data.ResConstantsDec}}

	{{data.ResTypes}}

	FROS{{data.UEName}}Res()
	{
		{{data.ResConstructor}}
	}

	void SetFromROS2(const {{data.Group}}__srv__{{data.NameCap}}_Response& in_ros_data)
	{
    	{{data.ResSetFromROS2}}
	}

	void SetROS2({{data.Group}}__srv__{{data.NameCap}}_Response& out_ros_data) const
	{
    	{{data.ResSetROS2}}
	}
};

UCLASS()
class {{data.ModuleAPI}} UROS2{{data.UEName}}Srv : public UROS2GenericSrv
{
	GENERATED_BODY()

public:
  	UFUNCTION(BlueprintCallable)
	virtual void Init() override;

  	UFUNCTION(BlueprintCallable)
	virtual void Fini() override;

	virtual const rosidl_service_type_support_t* GetTypeSupport() const override;
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void SetRequest(const FROS{{data.UEName}}Req& Request);
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void GetRequest(FROS{{data.UEName}}Req& Request) const;
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void SetResponse(const FROS{{data.UEName}}Res& Response);
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void GetResponse(FROS{{data.UEName}}Res& Response) const;
	
	virtual void* GetRequest() override;
	virtual void* GetResponse() override;

	{{data.ReqConstantsGetter}}
	{{data.ResConstantsGetter}}

private:
	virtual FString SrvRequestToString() const override;
	virtual FString SrvResponseToString() const override;

	{{data.Group}}__srv__{{data.NameCap}}_Request {{data.NameCap}}_req;
	{{data.Group}}__srv__{{data.NameCap}}_Response {{data.NameCap}}_res;
};
