args: #path is relative from home
  ue_path: UnrealEngine
  ue_proj_path: turtlebot3-UE 
  ue_plugin_name: rclUE 
  ue_plugin_folder_name: rclUE
  ue_target_3rd_name: ros # sub dir name under ThirdParty
  ue_target_ros_wrapper_path: '' # sub dir name under Source/<plugin name>/Public or Private.

# build and code gen target msgs
target_pkgs: 
  - 'action_msgs'
  - 'actionlib_msgs'
  - 'builtin_interfaces'
  - 'unique_identifier_msgs'
  - 'diagnostic_msgs'
  - 'rosgraph_msgs'
  - 'geometry_msgs'
  - 'nav_msgs'
  - 'sensor_msgs'
  - 'shape_msgs'
  - 'std_msgs'
  - 'std_srvs'
  - 'stereo_msgs'
  - 'trajectory_msgs'
  - 'visualization_msgs'
  - 'tf2_msgs'
  - 'pcl_msgs'
  # 'ackermann_msgs'
  - 'example_interfaces'
  - 'ue_msgs'


# msgs which is not copied to project.
black_list_msgs:
  - 'ROS2WStringMsg' # can't handle wstring in UE.
  #
  # array parser issue
  - 'ROS2CancelGoalSrv'
  - 'ROS2MeshMsg'
  - 'ROS2SolidPrimitiveMsg'
  #
  - 'ROS2TFMessageMsg' # memcpy/free issues. fixed version in rclUE but can't autogenerate.    
