ARG UBUNTU_VER="20.04"

FROM ubuntu:${UBUNTU_VER} 
ARG ROSDISTRO="foxy"
ARG UE5_DIR="/home/admin/UnrealEngine"

RUN apt update && apt install sudo -y

RUN adduser --disabled-password --gecos '' admin && \
    adduser admin sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER admin
WORKDIR /home/admin

RUN mkdir UE_tools

COPY --chown=admin:admin . UE_tools/

WORKDIR /home/admin/UE_tools

# install dependency
ENV DEBIAN_FRONTEND=noninteractive
RUN sudo apt install -y tzdata && \
    sudo apt install -y python3 python3-pip git wget curl software-properties-common && \
    sudo pip3 install -r requirements.txt

# build base libs and msgs
RUN --mount=type=bind,target=/home/admin/UE_tools/UE5/Engine/Extras,from=ue5_extras export UE5_DIR=/home/admin/UE_tools/UE5 && \
    echo $UE5_DIR && ls $UE5_DIR &&  ls /home/admin/UE_tools/UE5/Engine/Extras \
    python3 build_install_codegen.py --type base --build --rosdistro $ROSDISTRO && \
    python3 build_install_codegen.py --type pkgs --build --rosdistro $ROSDISTRO && \
    rm -r ros2_ws/src ros2_ws/build ros2_ws/log


ADD entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]